/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:18aed5d0-e65d-4efe-b102-2bcae8a0a71d",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_2Q3gl3EG1",
    "aws_user_pools_web_client_id": "1nrc8h2siugvjpeum0ggtj58ub",
    "oauth": {
        "domain": "mmob1c9544a5-1c9544a5-mmobdev.auth.eu-west-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://test.dev.service.mmob.com/dashboard/",
        "redirectSignOut": "https://test.dev.service.mmob.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
